on:
  pull_request:
    branches:
      - development
      - main
      - master
  push:
    tags:
      - run-tests-*
jobs:
  go_vulnerability:
    if: startsWith(github.head_ref, 'pulumi-github-actions') == false
    name: GO Vulnerability Check
    uses: NurseBuddy/shared-github-workflows/.github/workflows/go-vulnerability-check.yml@main
