on:
  push:
    tags:
      - sg-prod-*
      - sg-all-*
      - prod-all-*
      - all-*
jobs:
  push_to_sg_prod:
    uses: NurseBuddy/shared-github-workflows/.github/workflows/push-to-ecr.yml@main
    with:
      aws_region: ap-southeast-1
      aws_role_arn: ${{ vars.SG_PROD_AWS_ROLE_ARN}}
      ecr_url: ${{ vars.SG_PROD_ECR_URL}}
      ecs_service: ${{ vars.SG_PROD_ECS_SERVICE}}
      ecs_cluster: ${{ vars.SG_PROD_ECS_CLUSTER}}
name: Push To sg-prod ECR
permissions:
  id-token: write
  contents: read
